<a href="https://colab.research.google.com/github/arnav-116/python-for-data-science/blob/main/data_science02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd


In [5]:
arr = np.array([10,20,30,40,50])
print('Original Array:',arr)

Original Array: [10 20 30 40 50]


In [6]:
arr + 5

array([15, 25, 35, 45, 55])

In [7]:
arr*2


array([ 20,  40,  60,  80, 100])

In [8]:
arr[arr>25]

array([30, 40, 50])

In [15]:
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],'Age': [25, 30, 35, 40], 'Score': [85.5, 92.0, 88.0, 76.5 ]}

In [12]:
df = pd.DataFrame(data)
print("\nOrginal Dataframe\n",df)


Orginal Dataframe
       Name   Age  Score
0    Alice  25.3   85.5
1      Bob  30.0   92.0
2  Charlie  35.0   88.0
3    David  40.0   76.5


In [16]:
df['Passed'] = df['Score'] >= 80
print("\nDataFrame with 'Passed' column:\n", df)


DataFrame with 'Passed' column:
       Name   Age  Score  Passed
0    Alice  25.3   85.5    True
1      Bob  30.0   92.0    True
2  Charlie  35.0   88.0    True
3    David  40.0   76.5   False


In [17]:
older_students = df[df['Age'] > 30]
print("\nStudents older than 30:\n", older_students )


Students older than 30:
       Name   Age  Score  Passed
2  Charlie  35.0   88.0    True
3    David  40.0   76.5   False


In [18]:
average_score = df['Score'].mean()
print("\nAverage Score:", average_score )


Average Score: 85.5
